# -*- coding: utf-8 -*-
import math

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        ''' self.lineEdit = None
         self.pushButton_16 = None
         self.pushButton_35 = None
         self.pushButton_19 = None
         self.pushButton_18 = None
         self.pushButton_26 = None
         self.pushButton_27 = None
         self.pushButton_30 = None
         self.pushButton_23 = None
         self.pushButton_20 = None
         self.pushButton_24 = None
         self.pushButton_22 = None
         self.pushButton_32 = None
         self.pushButton_25 = None
         self.pushButton_31 = None
         self.pushButton_11 = None
         self.pushButton_13 = None
         self.pushButton_21 = None
         self.pushButton_33 = None
         self.pushButton_14 = None
         self.pushButton_28 = None
         self.pushButton_15 = None
         self.pushButton_12 = None
         self.pushButton_6 = None
         self.pushButton_9 = None
         self.pushButton_1 = None
         self.gridLayout = None
         self.gridLayoutWidget = None
         self.square = None
         self.pushButton_17 = None
 '''

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 615)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setEnabled(True)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 150, 550, 481))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(80, 40))
        self.gridLayoutWidget.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_1.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_1.setStyleSheet("#pushButton_1{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_1:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_9.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_9:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_3.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_3:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_6.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_6:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_15.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("#pushButton_15{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_15:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setEnabled(True)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_12.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_12:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_28.setEnabled(True)
        self.pushButton_28.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_28.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("#pushButton_28{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_28:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 5, 2, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_33.setEnabled(True)
        self.pushButton_33.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_33.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("#pushButton_33{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_33:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 6, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setEnabled(True)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_14.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("#pushButton_14{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_14:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 3, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setEnabled(True)
        self.pushButton_18.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_18.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("#pushButton_18{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_18:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 3, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setEnabled(True)
        self.pushButton_20.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_20.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("#pushButton_20{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_20:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 3, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setEnabled(True)
        self.pushButton_13.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_13.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("#pushButton_13{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_13:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setEnabled(True)
        self.pushButton_21.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_21.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("#pushButton_21{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_21:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 4, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setEnabled(True)
        self.pushButton_22.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_22.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("#pushButton_22{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_22:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 4, 1, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setEnabled(True)
        self.pushButton_31.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_31.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("#pushButton_31{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_31:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 6, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_11.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("#pushButton_11{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_11:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setEnabled(True)
        self.pushButton_32.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_32.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("#pushButton_32{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_32:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 6, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setEnabled(True)
        self.pushButton_24.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_24.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("#pushButton_24{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_24:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 4, 3, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setEnabled(True)
        self.pushButton_23.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_23.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("#pushButton_23{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_23:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 4, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setEnabled(True)
        self.pushButton_25.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_25.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("#pushButton_25{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_25:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 4, 4, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_27.setEnabled(True)
        self.pushButton_27.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_27.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("#pushButton_27{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "hover:#397c73;\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_27:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 5, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setEnabled(True)
        self.pushButton_26.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_26.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("#pushButton_26{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_26:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 5, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setEnabled(True)
        self.pushButton_16.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_16.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("#pushButton_16{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_16:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setEnabled(True)
        self.pushButton_30.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_30.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("#pushButton_30{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_30:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 5, 4, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_34.setEnabled(True)
        self.pushButton_34.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_34.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("#pushButton_34{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_34:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_34, 6, 3, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setEnabled(True)
        self.pushButton_29.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_29.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("#pushButton_29{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_29:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 5, 3, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_35.setEnabled(True)
        self.pushButton_35.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_35.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("#pushButton_35{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_35:hover{\n"
                                         "background-color:#5FD068;\n"
                                         "}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_35, 6, 4, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setEnabled(True)
        self.pushButton_17.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_17.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("#pushButton_17{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_17:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setEnabled(True)
        self.pushButton_19.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_19.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("#pushButton_19{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_19:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_4.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
                                        "background-color:red;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_4:hover{\n"
                                        "background-color:#FF884B;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_5.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
                                        "background-color:#e7dd89;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_5:hover{\n"
                                        "background-color:#FFD495;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_7.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_7:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_10.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
                                         "background-color:#b7a6a4;\n"
                                         "  color: #ffff;\n"
                                         "border-radius:5px;\n"
                                         "\n"
                                         "}\n"
                                         "#pushButton_10:hover{\n"
                                         "background-color:#002ead;\n"
                                         "}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_8.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "}\n"
                                        "#pushButton_8:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton_2.setSizeIncrement(QtCore.QSize(45, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
                                        "background-color:#b7a6a4;\n"
                                        "  color: #ffff;\n"
                                        "border-radius:5px;\n"
                                        "\n"
                                        "\n"
                                        "}\n"
                                        "#pushButton_2:hover{\n"
                                        "background-color:#002ead;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 551, 111))
        self.lineEdit.setSizeIncrement(QtCore.QSize(19, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("#lineEdit{\n"
                                    "  background-color: lightgrey;\n"
                                    "  color: blue;\n"
                                    "\n"
                                    "}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.lineEdit.setObjectName("lineEdit")
        # CONNECTION FROM THE BUTTON STARTS.........................................
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(self.pie)
        self.pushButton_3.clicked.connect(self.e)
        self.pushButton_4.clicked.connect(self.clr)
        self.pushButton_5.clicked.connect(self.dell)
        self.pushButton_17.clicked.connect(self.seven)
        self.pushButton_18.clicked.connect(self.eight)
        self.pushButton_19.clicked.connect(self.nine)

        self.pushButton_22.clicked.connect(self.four)
        self.pushButton_23.clicked.connect(self.five)
        self.pushButton_24.clicked.connect(self.six)

        self.pushButton_27.clicked.connect(self.one)
        self.pushButton_28.clicked.connect(self.two)
        self.pushButton_29.clicked.connect(self.three)

        self.pushButton_33.clicked.connect(self.zero)
        self.pushButton_6.clicked.connect(self.square)
        self.pushButton_7.clicked.connect(self.fraction)
        self.pushButton_8.clicked.connect(self.absolute)
        self.pushButton_10.clicked.connect(self.mod)
        self.pushButton_35.clicked.connect(self.equals)
        self.pushButton_9.clicked.connect(self.sin_)
        self.pushButton_11.clicked.connect(self.sqRoot)
        self.pushButton_14.clicked.connect(self.Factorial)
        self.pushButton_30.clicked.connect(self.addi)
        self.pushButton_25.clicked.connect(self.minus)
        self.pushButton_20.clicked.connect(self.multiplication)
        self.pushButton_15.clicked.connect(self.div)
        self.pushButton_34.clicked.connect(self.decimal)
        self.pushButton_26.clicked.connect(self.loga)
        self.pushButton_21.clicked.connect(self.Ten_power)
        self.pushButton_12.clicked.connect(self.cos_)
        self.pushButton_13.clicked.connect(self.tan_)
        self.pushButton_31.clicked.connect(self.LN)


        '''
        remaining functions
         self.pushButton_1.clicked.connect(self.push_2nd)
        self.pushButton_32.clicked.connect(self.abMinus)
        self.pushButton_16.clicked.connect(self.Power)

        '''

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.pushButton_1.setToolTip(_translate("Form",
                                                "<html><head/><body><p>2<span style=\" vertical-align:super;\">nd</span></p></body></html>"))
        self.pushButton_1.setWhatsThis(_translate("Form",
                                                  "<html><head/><body><p>2<span style=\" vertical-align:super;\">nd</span></p></body></html>"))
        self.pushButton_1.setText(_translate("Form", "2nd"))
        self.pushButton_9.setText(_translate("Form", "sin()"))
        self.pushButton_3.setText(_translate("Form", "e"))
        self.pushButton_6.setText(_translate("Form", "x²"))
        self.pushButton_15.setText(_translate("Form", "≑"))
        self.pushButton_12.setText(_translate("Form", "cos()"))
        self.pushButton_28.setText(_translate("Form", "2"))
        self.pushButton_33.setText(_translate("Form", "0"))
        self.pushButton_14.setText(_translate("Form", "n!"))
        self.pushButton_18.setText(_translate("Form", "8"))
        self.pushButton_20.setText(_translate("Form", "*"))
        self.pushButton_13.setText(_translate("Form", "tan()"))
        self.pushButton_21.setText(_translate("Form", "10^x"))
        self.pushButton_22.setText(_translate("Form", "4"))
        self.pushButton_31.setText(_translate("Form", "ln"))
        self.pushButton_11.setText(_translate("Form", "²√x"))
        self.pushButton_32.setText(_translate("Form", "∓"))
        self.pushButton_24.setText(_translate("Form", "6"))
        self.pushButton_23.setText(_translate("Form", "5"))
        self.pushButton_25.setText(_translate("Form", "-"))
        self.pushButton_27.setText(_translate("Form", "1"))
        self.pushButton_26.setText(_translate("Form", "log"))
        self.pushButton_16.setText(_translate("Form", "^"))
        self.pushButton_30.setText(_translate("Form", "+"))
        self.pushButton_34.setText(_translate("Form", "."))
        self.pushButton_29.setText(_translate("Form", "3"))
        self.pushButton_35.setText(_translate("Form", "="))
        self.pushButton_17.setText(_translate("Form", "7"))
        self.pushButton_19.setText(_translate("Form", "9"))
        self.pushButton_4.setText(_translate("Form", "CE"))
        self.pushButton_5.setText(_translate("Form", "⩤"))
        self.pushButton_7.setText(_translate("Form", "1/x"))
        self.pushButton_10.setText(_translate("Form", "mod"))
        self.pushButton_8.setText(_translate("Form", "|x|"))
        self.pushButton_2.setText(_translate("Form", "∏"))
        self.lineEdit.setPlaceholderText(_translate("Form", "0"))

    ##INILIZATION OF THE FUCTION CREATED----------------
    def pie(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str(math.pi))

    def e(self):

        self.lineEdit.setText(str(math.e))

    def clr(self):
        val = self.lineEdit.text()
        self.lineEdit.setText("")

    def dell(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val[:len(val) - 1])

    def one(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "1")

    def two(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "2")

    def three(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "3")

    def four(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "4")

    def five(self):

        val = self.lineEdit.text()
        self.lineEdit.setText(val + "5")

    def six(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "6")

    def seven(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "7")

    def eight(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "8")

    def nine(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "9")

    def zero(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "0")

    def square(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str((eval(val) ** 2)))

    def fraction(self):
        val = self.lineEdit.text()
        self.a = (1 / (eval(val)))
        self.lineEdit.setText(str(self.a))

    def absolute(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str((abs(eval(val)))))

    def mod(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "%")

    def equals(self):
        val = self.lineEdit.text()
        try:
            self.lineEdit.setText(str(eval(val)))
        except:
            self.lineEdit.setText("1")

    def sqRoot(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str((math.sqrt(eval(val)))))

    def Factorial(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str(int(math.factorial(eval(val)))))

    def addi(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "+")

    def minus(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "-")

    def multiplication(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "*")

    def div(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + "/")

    def decimal(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val + ".")

    def Ten_power(self):
        val = self.lineEdit.text()
        self.p = math.pow(10, eval(val))
        self.lineEdit.setText(str(self.p))

    def loga(self):

        val = self.lineEdit.text()
        self.p = math.log10(eval(val))
        self.lineEdit.setText(str(self.p))

    '''def abMinus(self):
        val = self.lineEdit.text()
        int: flag =0;
        check(flag,val)

    def check(f,v):
        if(f==0):
            self.lineEdit.setText()'''

    def cos_(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str(round(math.cos(math.radians(eval(val))))))

    def tan_(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str(round(math.tan(math.radians(eval(val))))))

    def sin_(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(str(round(math.sin(math.radians(eval(val))))))

    def LN(self):
        val = self.lineEdit.text()
        self.p = math.log(eval(val))
        self.lineEdit.setText(str(self.p))
    '''def Power(self):
        val = self.lineEdit.text()
        self.lineEdit.setText(val+"^")
        #val2= self.lineEdit.text()-len(val)
        #self.a=math.pow(eval(val),eval(val2))
        #self.lineEdit.setText(self.a)
        #val2=self.lineEdit.text()
        #self.a=pow(eval(val),eval(val2))

    '''

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
